# Generated by Django 3.1.6 on 2021-03-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prikaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер приказа')),
                ('date', models.DateField(verbose_name='Дата приказа')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
    ]
